language: python

python:
  - "2.7"

# command to install dependencies
install: 
  -  pip install -r example/requirements.txt --use-mirrors
  -  pip install coveralls --use-mirrors

# command to run tests
script: 
  -  python example/manage.py test blog_grids
  -  coverage run --source="." example/manage.py test blog_grids

after_success:
  - coveralls  
